// @generated by packages/catalog/scripts/proto-parser.ts - DO NOT EDIT

/**
 * Cursor protocol declarations used by Oh My Pi.
 *
 * Each declaration retains only fields consumed by the client or its protocol tests.
 */
import { pb, type MessageCodec, type ProtoMessage } from "./protobuf";

/** Cursor enum CursorRuleSource. */
export enum CursorRuleSource {
	UNSPECIFIED = 0,
	TEAM = 1,
	USER = 2,
}

/** Cursor enum ForceBackgroundShellStatus. */
export enum ForceBackgroundShellStatus {
	UNSPECIFIED = 0,
	ACCEPTED = 1,
	NOT_FOUND = 2,
}

/** Cursor enum ForceBackgroundSubagentStatus. */
export enum ForceBackgroundSubagentStatus {
	UNSPECIFIED = 0,
	ACCEPTED = 1,
	NOT_FOUND = 2,
}

/** Cursor enum InferenceMessageRole. */
export enum InferenceMessageRole {
	UNSPECIFIED = 0,
	USER = 1,
	ASSISTANT = 2,
	TOOL = 3,
	SYSTEM = 4,
}

/** Cursor enum InferenceReason. */
export enum InferenceReason {
	UNSPECIFIED = 0,
	GEMINI_VIDEO_SUBAGENT = 1,
}

/** Cursor enum InferenceStreamErrorType. */
export enum InferenceStreamErrorType {
	UNSPECIFIED = 0,
	UNKNOWN = 1,
	INPUT_TOKEN_LIMIT = 2,
	OUTPUT_TOKEN_LIMIT = 3,
	RATE_LIMIT = 4,
	AUTHENTICATION = 5,
	PERMISSION = 6,
	OVERLOADED = 7,
	CONTENT_FILTER = 8,
}

/** Cursor enum RunInferenceRoutingRole. */
export enum RunInferenceRoutingRole {
	UNSPECIFIED = 0,
	USER = 1,
	ASSISTANT = 2,
}

/** Cursor message agent.v1.ApiKeyCredentials. */
export interface ApiKeyCredentials extends ProtoMessage {
	apiKey: string;
	baseUrl?: string;
}

export const ApiKeyCredentialsSchema: MessageCodec<ApiKeyCredentials> = pb<ApiKeyCredentials>("agent.v1.ApiKeyCredentials", [
	{ no: 1, name: "apiKey", kind: "string" },
	{ no: 2, name: "baseUrl", kind: "string", optional: true },
]);

/** Cursor message agent.v1.AzureCredentials. */
export interface AzureCredentials extends ProtoMessage {
	apiKey: string;
	baseUrl: string;
	deployment: string;
}

export const AzureCredentialsSchema: MessageCodec<AzureCredentials> = pb<AzureCredentials>("agent.v1.AzureCredentials", [
	{ no: 1, name: "apiKey", kind: "string" },
	{ no: 2, name: "baseUrl", kind: "string" },
	{ no: 3, name: "deployment", kind: "string" },
]);

/** Cursor message agent.v1.BedrockCredentials. */
export interface BedrockCredentials extends ProtoMessage {
	accessKey: string;
	secretKey: string;
	region: string;
	sessionToken?: string;
}

export const BedrockCredentialsSchema: MessageCodec<BedrockCredentials> = pb<BedrockCredentials>("agent.v1.BedrockCredentials", [
	{ no: 1, name: "accessKey", kind: "string" },
	{ no: 2, name: "secretKey", kind: "string" },
	{ no: 3, name: "region", kind: "string" },
	{ no: 4, name: "sessionToken", kind: "string", optional: true },
]);

/** Cursor message agent.v1.GetUsableModelsRequest. */
export interface GetUsableModelsRequest extends ProtoMessage {
	customModelIds: string[];
}

export const GetUsableModelsRequestSchema: MessageCodec<GetUsableModelsRequest> = pb<GetUsableModelsRequest>("agent.v1.GetUsableModelsRequest", [
	{ no: 1, name: "customModelIds", kind: "string", repeat: true },
]);

/** Cursor message agent.v1.GetUsableModelsResponse. */
export interface GetUsableModelsResponse extends ProtoMessage {
	models: ModelDetails[];
}

export const GetUsableModelsResponseSchema: MessageCodec<GetUsableModelsResponse> = pb<GetUsableModelsResponse>("agent.v1.GetUsableModelsResponse", [
	{ no: 1, name: "models", kind: "message", T: () => ModelDetailsSchema, repeat: true },
]);

/** Cursor message aiserver.v1.InferenceAgentTool. */
export interface InferenceAgentTool extends ProtoMessage {
	name: string;
	description: string;
	parameters: Uint8Array;
	customToolFormat?: InferenceCustomToolFormat;
}

export const InferenceAgentToolSchema: MessageCodec<InferenceAgentTool> = pb<InferenceAgentTool>("aiserver.v1.InferenceAgentTool", [
	{ no: 1, name: "name", kind: "string" },
	{ no: 2, name: "description", kind: "string" },
	{ no: 3, name: "parameters", kind: "bytes" },
	{ no: 4, name: "customToolFormat", kind: "message", T: () => InferenceCustomToolFormatSchema },
]);

/** Cursor message aiserver.v1.InferenceAnthropicOptions. */
export interface InferenceAnthropicOptions extends ProtoMessage {
	cacheControl?: InferenceCacheControl;
}

export const InferenceAnthropicOptionsSchema: MessageCodec<InferenceAnthropicOptions> = pb<InferenceAnthropicOptions>("aiserver.v1.InferenceAnthropicOptions", [
	{ no: 1, name: "cacheControl", kind: "message", T: () => InferenceCacheControlSchema },
]);

/** Cursor message aiserver.v1.InferenceCacheControl. */
export interface InferenceCacheControl extends ProtoMessage {
	type: string;
}

export const InferenceCacheControlSchema: MessageCodec<InferenceCacheControl> = pb<InferenceCacheControl>("aiserver.v1.InferenceCacheControl", [
	{ no: 1, name: "type", kind: "string" },
]);

/** Cursor message aiserver.v1.InferenceContentPart. */
export interface InferenceContentPart extends ProtoMessage {
	part:
		| { case: undefined; value?: undefined }
		| { case: "text"; value: InferenceTextPart }
		| { case: "image"; value: InferenceImagePart }
		| { case: "file"; value: InferenceFilePart };
}

export const InferenceContentPartSchema: MessageCodec<InferenceContentPart> = pb<InferenceContentPart>("aiserver.v1.InferenceContentPart", [
	{
		kind: "oneof",
		name: "part",
		variants: [
			{ no: 1, name: "text", kind: "message", T: () => InferenceTextPartSchema },
			{ no: 2, name: "image", kind: "message", T: () => InferenceImagePartSchema },
			{ no: 3, name: "file", kind: "message", T: () => InferenceFilePartSchema },
		],
	},
]);

/** Cursor message aiserver.v1.InferenceContentParts. */
export interface InferenceContentParts extends ProtoMessage {
	parts: InferenceContentPart[];
}

export const InferenceContentPartsSchema: MessageCodec<InferenceContentParts> = pb<InferenceContentParts>("aiserver.v1.InferenceContentParts", [
	{ no: 1, name: "parts", kind: "message", T: () => InferenceContentPartSchema, repeat: true },
]);

/** Cursor message aiserver.v1.InferenceCoreMessage. */
export interface InferenceCoreMessage extends ProtoMessage {
	role: InferenceMessageRole;
	toolCalls: InferenceToolCall[];
	reasoningParts: InferenceReasoningPart[];
	modelProviderMessageId?: string;
	openaiPhase?: string;
	openaiPhaseNull?: boolean;
	cursorInferenceReason?: string;
	cursorFeatureType?: string;
	content:
		| { case: undefined; value?: undefined }
		| { case: "text"; value: string }
		| { case: "parts"; value: InferenceContentParts }
		| { case: "toolContent"; value: InferenceToolResultContent };
}

export const InferenceCoreMessageSchema: MessageCodec<InferenceCoreMessage> = pb<InferenceCoreMessage>("aiserver.v1.InferenceCoreMessage", [
	{ no: 1, name: "role", kind: "enum" },
	{ no: 4, name: "toolCalls", kind: "message", T: () => InferenceToolCallSchema, repeat: true },
	{ no: 7, name: "reasoningParts", kind: "message", T: () => InferenceReasoningPartSchema, repeat: true },
	{ no: 8, name: "modelProviderMessageId", kind: "string", optional: true },
	{ no: 9, name: "openaiPhase", kind: "string", optional: true },
	{ no: 10, name: "openaiPhaseNull", kind: "bool", optional: true },
	{ no: 11, name: "cursorInferenceReason", kind: "string", optional: true },
	{ no: 12, name: "cursorFeatureType", kind: "string", optional: true },
	{
		kind: "oneof",
		name: "content",
		variants: [
			{ no: 2, name: "text", kind: "string" },
			{ no: 3, name: "parts", kind: "message", T: () => InferenceContentPartsSchema },
			{ no: 6, name: "toolContent", kind: "message", T: () => InferenceToolResultContentSchema },
		],
	},
]);

/** Cursor message aiserver.v1.InferenceCursorOptions. */
export interface InferenceCursorOptions extends ProtoMessage {
	imageDescription?: string;
	imageDescriptions: Record<string, string>;
}

export const InferenceCursorOptionsSchema: MessageCodec<InferenceCursorOptions> = pb<InferenceCursorOptions>("aiserver.v1.InferenceCursorOptions", [
	{ no: 1, name: "imageDescription", kind: "string", optional: true },
	{ no: 2, name: "imageDescriptions", kind: "map", K: "string", V: "string" },
]);

/** Cursor message aiserver.v1.InferenceCustomToolFormat. */
export interface InferenceCustomToolFormat extends ProtoMessage {
	type: string;
	definition: string;
	syntax: string;
}

export const InferenceCustomToolFormatSchema: MessageCodec<InferenceCustomToolFormat> = pb<InferenceCustomToolFormat>("aiserver.v1.InferenceCustomToolFormat", [
	{ no: 1, name: "type", kind: "string" },
	{ no: 2, name: "definition", kind: "string" },
	{ no: 3, name: "syntax", kind: "string" },
]);

/** Cursor message aiserver.v1.InferenceExtendedUsageInfo. */
export interface InferenceExtendedUsageInfo extends ProtoMessage {
	inputTokens: number;
	outputTokens: number;
	cacheReadTokens: number;
	cacheWriteTokens: number;
	maxTokens: number;
}

export const InferenceExtendedUsageInfoSchema: MessageCodec<InferenceExtendedUsageInfo> = pb<InferenceExtendedUsageInfo>("aiserver.v1.InferenceExtendedUsageInfo", [
	{ no: 1, name: "inputTokens", kind: "int32" },
	{ no: 2, name: "outputTokens", kind: "int32" },
	{ no: 3, name: "cacheReadTokens", kind: "int32" },
	{ no: 4, name: "cacheWriteTokens", kind: "int32" },
	{ no: 5, name: "maxTokens", kind: "int32" },
]);

/** Cursor message aiserver.v1.InferenceExtraData. */
export interface InferenceExtraData extends ProtoMessage {
	tokenLogprobs: InferenceTokenLogprobs[];
	tokenIds: InferenceTokenIds[];
	promptTokenIds: InferenceTokenIds[];
	extraTokens: InferenceTokenIds[];
	extraLogprobs: InferenceTokenLogprobs[];
	routingMatrix: InferenceRoutingRow[];
}

export const InferenceExtraDataSchema: MessageCodec<InferenceExtraData> = pb<InferenceExtraData>("aiserver.v1.InferenceExtraData", [
	{ no: 1, name: "tokenLogprobs", kind: "message", T: () => InferenceTokenLogprobsSchema, repeat: true },
	{ no: 2, name: "tokenIds", kind: "message", T: () => InferenceTokenIdsSchema, repeat: true },
	{ no: 3, name: "promptTokenIds", kind: "message", T: () => InferenceTokenIdsSchema, repeat: true },
	{ no: 4, name: "extraTokens", kind: "message", T: () => InferenceTokenIdsSchema, repeat: true },
	{ no: 5, name: "extraLogprobs", kind: "message", T: () => InferenceTokenLogprobsSchema, repeat: true },
	{ no: 6, name: "routingMatrix", kind: "message", T: () => InferenceRoutingRowSchema, repeat: true },
]);

/** Cursor message aiserver.v1.InferenceFilePart. */
export interface InferenceFilePart extends ProtoMessage {
	data: string;
	mediaType: string;
	filename?: string;
	providerOptions?: InferenceProviderOptions;
}

export const InferenceFilePartSchema: MessageCodec<InferenceFilePart> = pb<InferenceFilePart>("aiserver.v1.InferenceFilePart", [
	{ no: 1, name: "data", kind: "string" },
	{ no: 2, name: "mediaType", kind: "string" },
	{ no: 3, name: "filename", kind: "string", optional: true },
	{ no: 4, name: "providerOptions", kind: "message", T: () => InferenceProviderOptionsSchema },
]);

/** Cursor message aiserver.v1.InferenceImageDescription. */
export interface InferenceImageDescription extends ProtoMessage {
	messageIndex: number;
	partIndex: number;
	expContentIndex?: number;
	description: string;
}

export const InferenceImageDescriptionSchema: MessageCodec<InferenceImageDescription> = pb<InferenceImageDescription>("aiserver.v1.InferenceImageDescription", [
	{ no: 1, name: "messageIndex", kind: "int32" },
	{ no: 2, name: "partIndex", kind: "int32" },
	{ no: 3, name: "expContentIndex", kind: "int32", optional: true },
	{ no: 4, name: "description", kind: "string" },
]);

/** Cursor message aiserver.v1.InferenceImageDescriptionsInfo. */
export interface InferenceImageDescriptionsInfo extends ProtoMessage {
	descriptions: InferenceImageDescription[];
}

export const InferenceImageDescriptionsInfoSchema: MessageCodec<InferenceImageDescriptionsInfo> = pb<InferenceImageDescriptionsInfo>("aiserver.v1.InferenceImageDescriptionsInfo", [
	{ no: 1, name: "descriptions", kind: "message", T: () => InferenceImageDescriptionSchema, repeat: true },
]);

/** Cursor message aiserver.v1.InferenceImagePart. */
export interface InferenceImagePart extends ProtoMessage {
	data: string;
	mimeType?: string;
	providerOptions?: InferenceProviderOptions;
}

export const InferenceImagePartSchema: MessageCodec<InferenceImagePart> = pb<InferenceImagePart>("aiserver.v1.InferenceImagePart", [
	{ no: 1, name: "data", kind: "string" },
	{ no: 2, name: "mimeType", kind: "string", optional: true },
	{ no: 3, name: "providerOptions", kind: "message", T: () => InferenceProviderOptionsSchema },
]);

/** Cursor message aiserver.v1.InferenceInvocationIdInfo. */
export interface InferenceInvocationIdInfo extends ProtoMessage {
	invocationId: string;
}

export const InferenceInvocationIdInfoSchema: MessageCodec<InferenceInvocationIdInfo> = pb<InferenceInvocationIdInfo>("aiserver.v1.InferenceInvocationIdInfo", [
	{ no: 1, name: "invocationId", kind: "string" },
]);

/** Cursor message aiserver.v1.InferenceModelConfig. */
export interface InferenceModelConfig extends ProtoMessage {
	maxTokens?: number;
	temperature?: number;
	topP?: number;
	stopSequences: string[];
}

export const InferenceModelConfigSchema: MessageCodec<InferenceModelConfig> = pb<InferenceModelConfig>("aiserver.v1.InferenceModelConfig", [
	{ no: 1, name: "maxTokens", kind: "int32", optional: true },
	{ no: 2, name: "temperature", kind: "float", optional: true },
	{ no: 3, name: "topP", kind: "float", optional: true },
	{ no: 4, name: "stopSequences", kind: "string", repeat: true },
]);

/** Cursor message aiserver.v1.InferenceModelParameterValue. */
export interface InferenceModelParameterValue extends ProtoMessage {
	id: string;
	value: string;
}

export const InferenceModelParameterValueSchema: MessageCodec<InferenceModelParameterValue> = pb<InferenceModelParameterValue>("aiserver.v1.InferenceModelParameterValue", [
	{ no: 1, name: "id", kind: "string" },
	{ no: 2, name: "value", kind: "string" },
]);

/** Cursor message aiserver.v1.InferenceNamedProviderDefinedTool. */
export interface InferenceNamedProviderDefinedTool extends ProtoMessage {
	name: string;
	id: string;
	type: string;
	options: Uint8Array;
}

export const InferenceNamedProviderDefinedToolSchema: MessageCodec<InferenceNamedProviderDefinedTool> = pb<InferenceNamedProviderDefinedTool>("aiserver.v1.InferenceNamedProviderDefinedTool", [
	{ no: 1, name: "name", kind: "string" },
	{ no: 2, name: "id", kind: "string" },
	{ no: 3, name: "type", kind: "string" },
	{ no: 4, name: "options", kind: "bytes" },
]);

/** Cursor message aiserver.v1.InferenceProviderMetadataInfo. */
export interface InferenceProviderMetadataInfo extends ProtoMessage {
	metadata: Uint8Array;
}

export const InferenceProviderMetadataInfoSchema: MessageCodec<InferenceProviderMetadataInfo> = pb<InferenceProviderMetadataInfo>("aiserver.v1.InferenceProviderMetadataInfo", [
	{ no: 1, name: "metadata", kind: "bytes" },
]);

/** Cursor message aiserver.v1.InferenceProviderOptions. */
export interface InferenceProviderOptions extends ProtoMessage {
	anthropic?: InferenceAnthropicOptions;
	cursor?: InferenceCursorOptions;
}

export const InferenceProviderOptionsSchema: MessageCodec<InferenceProviderOptions> = pb<InferenceProviderOptions>("aiserver.v1.InferenceProviderOptions", [
	{ no: 1, name: "anthropic", kind: "message", T: () => InferenceAnthropicOptionsSchema },
	{ no: 2, name: "cursor", kind: "message", T: () => InferenceCursorOptionsSchema },
]);

/** Cursor message aiserver.v1.InferenceReasoningPart. */
export interface InferenceReasoningPart extends ProtoMessage {
	isRedacted: boolean;
	text: string;
	signature?: string;
	redactedData?: string;
	modelName?: string;
}

export const InferenceReasoningPartSchema: MessageCodec<InferenceReasoningPart> = pb<InferenceReasoningPart>("aiserver.v1.InferenceReasoningPart", [
	{ no: 1, name: "isRedacted", kind: "bool" },
	{ no: 2, name: "text", kind: "string" },
	{ no: 3, name: "signature", kind: "string", optional: true },
	{ no: 4, name: "redactedData", kind: "string", optional: true },
	{ no: 5, name: "modelName", kind: "string", optional: true },
]);

/** Cursor message aiserver.v1.InferenceRequestedModel. */
export interface InferenceRequestedModel extends ProtoMessage {
	modelId: string;
	maxMode: boolean;
	parameters: InferenceModelParameterValue[];
	builtInModel: boolean;
	isVariantStringRepresentation: boolean;
}

export const InferenceRequestedModelSchema: MessageCodec<InferenceRequestedModel> = pb<InferenceRequestedModel>("aiserver.v1.InferenceRequestedModel", [
	{ no: 1, name: "modelId", kind: "string" },
	{ no: 2, name: "maxMode", kind: "bool" },
	{ no: 3, name: "parameters", kind: "message", T: () => InferenceModelParameterValueSchema, repeat: true },
	{ no: 4, name: "builtInModel", kind: "bool" },
	{ no: 5, name: "isVariantStringRepresentation", kind: "bool" },
]);

/** Cursor message aiserver.v1.InferenceResponseInfo. */
export interface InferenceResponseInfo extends ProtoMessage {
	id: string;
	model: string;
	createdAt: bigint;
	messages: InferenceResponseMessage[];
	errorMessage?: string;
	inferenceExtraData?: InferenceExtraData;
	supportsSelfSummary?: boolean;
}

export const InferenceResponseInfoSchema: MessageCodec<InferenceResponseInfo> = pb<InferenceResponseInfo>("aiserver.v1.InferenceResponseInfo", [
	{ no: 1, name: "id", kind: "string" },
	{ no: 2, name: "model", kind: "string" },
	{ no: 3, name: "createdAt", kind: "int64" },
	{ no: 4, name: "messages", kind: "message", T: () => InferenceResponseMessageSchema, repeat: true },
	{ no: 5, name: "errorMessage", kind: "string", optional: true },
	{ no: 6, name: "inferenceExtraData", kind: "message", T: () => InferenceExtraDataSchema },
	{ no: 7, name: "supportsSelfSummary", kind: "bool", optional: true },
]);

/** Cursor message aiserver.v1.InferenceResponseMessage. */
export interface InferenceResponseMessage extends ProtoMessage {
	id: string;
	role: InferenceMessageRole;
	content?: string;
	toolCalls: InferenceToolCall[];
	toolResult?: InferenceToolResultContent;
	reasoningParts: InferenceReasoningPart[];
}

export const InferenceResponseMessageSchema: MessageCodec<InferenceResponseMessage> = pb<InferenceResponseMessage>("aiserver.v1.InferenceResponseMessage", [
	{ no: 1, name: "id", kind: "string" },
	{ no: 2, name: "role", kind: "enum" },
	{ no: 3, name: "content", kind: "string", optional: true },
	{ no: 4, name: "toolCalls", kind: "message", T: () => InferenceToolCallSchema, repeat: true },
	{ no: 5, name: "toolResult", kind: "message", T: () => InferenceToolResultContentSchema },
	{ no: 6, name: "reasoningParts", kind: "message", T: () => InferenceReasoningPartSchema, repeat: true },
]);

/** Cursor message aiserver.v1.InferenceRoutingRow. */
export interface InferenceRoutingRow extends ProtoMessage {
	values: string[];
}

export const InferenceRoutingRowSchema: MessageCodec<InferenceRoutingRow> = pb<InferenceRoutingRow>("aiserver.v1.InferenceRoutingRow", [
	{ no: 1, name: "values", kind: "string", repeat: true },
]);

/** Cursor message aiserver.v1.InferenceStreamError. */
export interface InferenceStreamError extends ProtoMessage {
	message: string;
	code: string;
	isInputTokenLimitError: boolean;
	isOutputTokenLimitError: boolean;
	errorType: InferenceStreamErrorType;
}

export const InferenceStreamErrorSchema: MessageCodec<InferenceStreamError> = pb<InferenceStreamError>("aiserver.v1.InferenceStreamError", [
	{ no: 1, name: "message", kind: "string" },
	{ no: 2, name: "code", kind: "string" },
	{ no: 3, name: "isInputTokenLimitError", kind: "bool" },
	{ no: 4, name: "isOutputTokenLimitError", kind: "bool" },
	{ no: 5, name: "errorType", kind: "enum" },
]);

/** Cursor message aiserver.v1.InferenceStreamRequest. */
export interface InferenceStreamRequest extends ProtoMessage {
	messages: InferenceCoreMessage[];
	tools: InferenceAgentTool[];
	providerDefinedTools: InferenceNamedProviderDefinedTool[];
	modelConfig?: InferenceModelConfig;
	modelId?: string;
	invocationId?: string;
	requestedModel?: InferenceRequestedModel;
	conversationId?: string;
	acceptedUnadvertisedToolNames: string[];
	automationId?: string;
	inferenceReason?: InferenceReason;
	conversationGroupId?: string;
}

export const InferenceStreamRequestSchema: MessageCodec<InferenceStreamRequest> = pb<InferenceStreamRequest>("aiserver.v1.InferenceStreamRequest", [
	{ no: 1, name: "messages", kind: "message", T: () => InferenceCoreMessageSchema, repeat: true },
	{ no: 2, name: "tools", kind: "message", T: () => InferenceAgentToolSchema, repeat: true },
	{ no: 3, name: "providerDefinedTools", kind: "message", T: () => InferenceNamedProviderDefinedToolSchema, repeat: true },
	{ no: 4, name: "modelConfig", kind: "message", T: () => InferenceModelConfigSchema },
	{ no: 5, name: "modelId", kind: "string", optional: true },
	{ no: 6, name: "invocationId", kind: "string", optional: true },
	{ no: 7, name: "requestedModel", kind: "message", T: () => InferenceRequestedModelSchema },
	{ no: 8, name: "conversationId", kind: "string", optional: true },
	{ no: 9, name: "acceptedUnadvertisedToolNames", kind: "string", repeat: true },
	{ no: 10, name: "automationId", kind: "string", optional: true },
	{ no: 11, name: "inferenceReason", kind: "enum", optional: true },
	{ no: 12, name: "conversationGroupId", kind: "string", optional: true },
]);

/** Cursor message aiserver.v1.InferenceStreamResponse. */
export interface InferenceStreamResponse extends ProtoMessage {
	response:
		| { case: undefined; value?: undefined }
		| { case: "textPart"; value: InferenceTextStreamPart }
		| { case: "toolCallPart"; value: InferenceToolCallStreamPart }
		| { case: "usage"; value: InferenceUsageInfo }
		| { case: "responseInfo"; value: InferenceResponseInfo }
		| { case: "extendedUsage"; value: InferenceExtendedUsageInfo }
		| { case: "providerMetadata"; value: InferenceProviderMetadataInfo }
		| { case: "invocationId"; value: InferenceInvocationIdInfo }
		| { case: "error"; value: InferenceStreamError }
		| { case: "thinkingPart"; value: InferenceThinkingStreamPart }
		| { case: "imageDescriptions"; value: InferenceImageDescriptionsInfo };
}

export const InferenceStreamResponseSchema: MessageCodec<InferenceStreamResponse> = pb<InferenceStreamResponse>("aiserver.v1.InferenceStreamResponse", [
	{
		kind: "oneof",
		name: "response",
		variants: [
			{ no: 1, name: "textPart", kind: "message", T: () => InferenceTextStreamPartSchema },
			{ no: 2, name: "toolCallPart", kind: "message", T: () => InferenceToolCallStreamPartSchema },
			{ no: 3, name: "usage", kind: "message", T: () => InferenceUsageInfoSchema },
			{ no: 4, name: "responseInfo", kind: "message", T: () => InferenceResponseInfoSchema },
			{ no: 5, name: "extendedUsage", kind: "message", T: () => InferenceExtendedUsageInfoSchema },
			{ no: 6, name: "providerMetadata", kind: "message", T: () => InferenceProviderMetadataInfoSchema },
			{ no: 7, name: "invocationId", kind: "message", T: () => InferenceInvocationIdInfoSchema },
			{ no: 8, name: "error", kind: "message", T: () => InferenceStreamErrorSchema },
			{ no: 9, name: "thinkingPart", kind: "message", T: () => InferenceThinkingStreamPartSchema },
			{ no: 10, name: "imageDescriptions", kind: "message", T: () => InferenceImageDescriptionsInfoSchema },
		],
	},
]);

/** Cursor message aiserver.v1.InferenceTextPart. */
export interface InferenceTextPart extends ProtoMessage {
	text: string;
	providerOptions?: InferenceProviderOptions;
}

export const InferenceTextPartSchema: MessageCodec<InferenceTextPart> = pb<InferenceTextPart>("aiserver.v1.InferenceTextPart", [
	{ no: 1, name: "text", kind: "string" },
	{ no: 2, name: "providerOptions", kind: "message", T: () => InferenceProviderOptionsSchema },
]);

/** Cursor message aiserver.v1.InferenceTextStreamPart. */
export interface InferenceTextStreamPart extends ProtoMessage {
	text: string;
	isFinal: boolean;
}

export const InferenceTextStreamPartSchema: MessageCodec<InferenceTextStreamPart> = pb<InferenceTextStreamPart>("aiserver.v1.InferenceTextStreamPart", [
	{ no: 1, name: "text", kind: "string" },
	{ no: 2, name: "isFinal", kind: "bool" },
]);

/** Cursor message aiserver.v1.InferenceThinkingStreamPart. */
export interface InferenceThinkingStreamPart extends ProtoMessage {
	text: string;
	signature?: string;
	isFinal: boolean;
}

export const InferenceThinkingStreamPartSchema: MessageCodec<InferenceThinkingStreamPart> = pb<InferenceThinkingStreamPart>("aiserver.v1.InferenceThinkingStreamPart", [
	{ no: 1, name: "text", kind: "string" },
	{ no: 2, name: "signature", kind: "string", optional: true },
	{ no: 3, name: "isFinal", kind: "bool" },
]);

/** Cursor message aiserver.v1.InferenceTokenIds. */
export interface InferenceTokenIds extends ProtoMessage {
	values: bigint[];
}

export const InferenceTokenIdsSchema: MessageCodec<InferenceTokenIds> = pb<InferenceTokenIds>("aiserver.v1.InferenceTokenIds", [
	{ no: 1, name: "values", kind: "int64", repeat: true },
]);

/** Cursor message aiserver.v1.InferenceTokenLogprobs. */
export interface InferenceTokenLogprobs extends ProtoMessage {
	values: number[];
}

export const InferenceTokenLogprobsSchema: MessageCodec<InferenceTokenLogprobs> = pb<InferenceTokenLogprobs>("aiserver.v1.InferenceTokenLogprobs", [
	{ no: 1, name: "values", kind: "double", repeat: true },
]);

/** Cursor message aiserver.v1.InferenceToolCall. */
export interface InferenceToolCall extends ProtoMessage {
	toolCallId: string;
	toolName: string;
	args: Uint8Array;
	rawToolCallArgs?: string;
}

export const InferenceToolCallSchema: MessageCodec<InferenceToolCall> = pb<InferenceToolCall>("aiserver.v1.InferenceToolCall", [
	{ no: 1, name: "toolCallId", kind: "string" },
	{ no: 2, name: "toolName", kind: "string" },
	{ no: 3, name: "args", kind: "bytes" },
	{ no: 4, name: "rawToolCallArgs", kind: "string", optional: true },
]);

/** Cursor message aiserver.v1.InferenceToolCallStreamPart. */
export interface InferenceToolCallStreamPart extends ProtoMessage {
	toolCallId: string;
	toolName: string;
	args: string;
	isComplete: boolean;
	toolIndex?: number;
}

export const InferenceToolCallStreamPartSchema: MessageCodec<InferenceToolCallStreamPart> = pb<InferenceToolCallStreamPart>("aiserver.v1.InferenceToolCallStreamPart", [
	{ no: 1, name: "toolCallId", kind: "string" },
	{ no: 2, name: "toolName", kind: "string" },
	{ no: 3, name: "args", kind: "string" },
	{ no: 4, name: "isComplete", kind: "bool" },
	{ no: 5, name: "toolIndex", kind: "int32", optional: true },
]);

/** Cursor message aiserver.v1.InferenceToolResultContent. */
export interface InferenceToolResultContent extends ProtoMessage {
	parts: InferenceToolResultPart[];
}

export const InferenceToolResultContentSchema: MessageCodec<InferenceToolResultContent> = pb<InferenceToolResultContent>("aiserver.v1.InferenceToolResultContent", [
	{ no: 1, name: "parts", kind: "message", T: () => InferenceToolResultPartSchema, repeat: true },
]);

/** Cursor message aiserver.v1.InferenceToolResultPart. */
export interface InferenceToolResultPart extends ProtoMessage {
	toolCallId: string;
	toolName: string;
	result: Uint8Array;
	isError: boolean;
	experimentalContent: InferenceContentPart[];
	providerOptions?: InferenceProviderOptions;
}

export const InferenceToolResultPartSchema: MessageCodec<InferenceToolResultPart> = pb<InferenceToolResultPart>("aiserver.v1.InferenceToolResultPart", [
	{ no: 1, name: "toolCallId", kind: "string" },
	{ no: 2, name: "toolName", kind: "string" },
	{ no: 3, name: "result", kind: "bytes" },
	{ no: 4, name: "isError", kind: "bool" },
	{ no: 5, name: "experimentalContent", kind: "message", T: () => InferenceContentPartSchema, repeat: true },
	{ no: 6, name: "providerOptions", kind: "message", T: () => InferenceProviderOptionsSchema },
]);

/** Cursor message aiserver.v1.InferenceUsageInfo. */
export interface InferenceUsageInfo extends ProtoMessage {
	promptTokens: number;
	completionTokens: number;
	totalTokens?: number;
}

export const InferenceUsageInfoSchema: MessageCodec<InferenceUsageInfo> = pb<InferenceUsageInfo>("aiserver.v1.InferenceUsageInfo", [
	{ no: 1, name: "promptTokens", kind: "int32" },
	{ no: 2, name: "completionTokens", kind: "int32" },
	{ no: 3, name: "totalTokens", kind: "int32", optional: true },
]);

/** Cursor message agent.v1.ModelDetails. */
export interface ModelDetails extends ProtoMessage {
	modelId: string;
	displayModelId: string;
	displayName: string;
	displayNameShort: string;
	aliases: string[];
	thinkingDetails?: ThinkingDetails;
	maxMode?: boolean;
	credentials:
		| { case: undefined; value?: undefined }
		| { case: "apiKeyCredentials"; value: ApiKeyCredentials }
		| { case: "azureCredentials"; value: AzureCredentials }
		| { case: "bedrockCredentials"; value: BedrockCredentials };
}

export const ModelDetailsSchema: MessageCodec<ModelDetails> = pb<ModelDetails>("agent.v1.ModelDetails", [
	{ no: 1, name: "modelId", kind: "string" },
	{ no: 3, name: "displayModelId", kind: "string" },
	{ no: 4, name: "displayName", kind: "string" },
	{ no: 5, name: "displayNameShort", kind: "string" },
	{ no: 6, name: "aliases", kind: "string", repeat: true },
	{ no: 2, name: "thinkingDetails", kind: "message", T: () => ThinkingDetailsSchema },
	{ no: 7, name: "maxMode", kind: "bool", optional: true },
	{
		kind: "oneof",
		name: "credentials",
		variants: [
			{ no: 8, name: "apiKeyCredentials", kind: "message", T: () => ApiKeyCredentialsSchema },
			{ no: 9, name: "azureCredentials", kind: "message", T: () => AzureCredentialsSchema },
			{ no: 10, name: "bedrockCredentials", kind: "message", T: () => BedrockCredentialsSchema },
		],
	},
]);

/** Cursor message aiserver.v1.RunInferenceCancelInvocation. */
export interface RunInferenceCancelInvocation extends ProtoMessage {
	invocationId: string;
}

export const RunInferenceCancelInvocationSchema: MessageCodec<RunInferenceCancelInvocation> = pb<RunInferenceCancelInvocation>("aiserver.v1.RunInferenceCancelInvocation", [
	{ no: 1, name: "invocationId", kind: "string" },
]);

/** Cursor message aiserver.v1.RunInferenceClientMessage. */
export interface RunInferenceClientMessage extends ProtoMessage {
	message:
		| { case: undefined; value?: undefined }
		| { case: "runRequest"; value: RunInferenceRunRequest }
		| { case: "invokeModel"; value: RunInferenceInvokeModel }
		| { case: "cancelInvocation"; value: RunInferenceCancelInvocation }
		| { case: "finishRun"; value: RunInferenceFinishRun };
}

export const RunInferenceClientMessageSchema: MessageCodec<RunInferenceClientMessage> = pb<RunInferenceClientMessage>("aiserver.v1.RunInferenceClientMessage", [
	{
		kind: "oneof",
		name: "message",
		variants: [
			{ no: 1, name: "runRequest", kind: "message", T: () => RunInferenceRunRequestSchema },
			{ no: 2, name: "invokeModel", kind: "message", T: () => RunInferenceInvokeModelSchema },
			{ no: 3, name: "cancelInvocation", kind: "message", T: () => RunInferenceCancelInvocationSchema },
			{ no: 4, name: "finishRun", kind: "message", T: () => RunInferenceFinishRunSchema },
		],
	},
]);

/** Cursor message aiserver.v1.RunInferenceErrorDetail. */
export interface RunInferenceErrorDetail extends ProtoMessage {
	type: string;
	value: Uint8Array;
}

export const RunInferenceErrorDetailSchema: MessageCodec<RunInferenceErrorDetail> = pb<RunInferenceErrorDetail>("aiserver.v1.RunInferenceErrorDetail", [
	{ no: 1, name: "type", kind: "string" },
	{ no: 2, name: "value", kind: "bytes" },
]);

/** Cursor message aiserver.v1.RunInferenceFinishRun. */
export interface RunInferenceFinishRun extends ProtoMessage {
}

export const RunInferenceFinishRunSchema: MessageCodec<RunInferenceFinishRun> = pb<RunInferenceFinishRun>("aiserver.v1.RunInferenceFinishRun", [
]);

/** Cursor message aiserver.v1.RunInferenceHeartbeat. */
export interface RunInferenceHeartbeat extends ProtoMessage {
}

export const RunInferenceHeartbeatSchema: MessageCodec<RunInferenceHeartbeat> = pb<RunInferenceHeartbeat>("aiserver.v1.RunInferenceHeartbeat", [
]);

/** Cursor message aiserver.v1.RunInferenceInvocationEnd. */
export interface RunInferenceInvocationEnd extends ProtoMessage {
	invocationId: string;
	error?: RunInferenceInvocationError;
}

export const RunInferenceInvocationEndSchema: MessageCodec<RunInferenceInvocationEnd> = pb<RunInferenceInvocationEnd>("aiserver.v1.RunInferenceInvocationEnd", [
	{ no: 1, name: "invocationId", kind: "string" },
	{ no: 2, name: "error", kind: "message", T: () => RunInferenceInvocationErrorSchema },
]);

/** Cursor message aiserver.v1.RunInferenceInvocationError. */
export interface RunInferenceInvocationError extends ProtoMessage {
	code: number;
	message: string;
	details: RunInferenceErrorDetail[];
}

export const RunInferenceInvocationErrorSchema: MessageCodec<RunInferenceInvocationError> = pb<RunInferenceInvocationError>("aiserver.v1.RunInferenceInvocationError", [
	{ no: 1, name: "code", kind: "int32" },
	{ no: 2, name: "message", kind: "string" },
	{ no: 3, name: "details", kind: "message", T: () => RunInferenceErrorDetailSchema, repeat: true },
]);

/** Cursor message aiserver.v1.RunInferenceInvocationResponse. */
export interface RunInferenceInvocationResponse extends ProtoMessage {
	invocationId: string;
	response?: InferenceStreamResponse;
}

export const RunInferenceInvocationResponseSchema: MessageCodec<RunInferenceInvocationResponse> = pb<RunInferenceInvocationResponse>("aiserver.v1.RunInferenceInvocationResponse", [
	{ no: 1, name: "invocationId", kind: "string" },
	{ no: 2, name: "response", kind: "message", T: () => InferenceStreamResponseSchema },
]);

/** Cursor message aiserver.v1.RunInferenceInvokeModel. */
export interface RunInferenceInvokeModel extends ProtoMessage {
	invocationId: string;
	request?: InferenceStreamRequest;
}

export const RunInferenceInvokeModelSchema: MessageCodec<RunInferenceInvokeModel> = pb<RunInferenceInvokeModel>("aiserver.v1.RunInferenceInvokeModel", [
	{ no: 1, name: "invocationId", kind: "string" },
	{ no: 2, name: "request", kind: "message", T: () => InferenceStreamRequestSchema },
]);

/** Cursor message aiserver.v1.RunInferencePromptModelMetadata. */
export interface RunInferencePromptModelMetadata extends ProtoMessage {
	vendor: string;
	promptVersion: string;
	isSonnet45: boolean;
	isGemini3: boolean;
	isGpt51: boolean;
	isGpt52: boolean;
	isGpt5: boolean;
	isGpt55: boolean;
	isGpt56: boolean;
	isSonnet4: boolean;
	isCodexFamily: boolean;
	isGpt54: boolean;
	isGpt52Codex: boolean;
	isGpt53Codex: boolean;
	isGpt53CodexSpark: boolean;
	isClaude4x: boolean;
	isOpus45: boolean;
	isOpus46: boolean;
	isOpus48: boolean;
	isOpus5: boolean;
	isFable5: boolean;
	isFruitcake: boolean;
	isGpt5Family: boolean;
	isComposer1: boolean;
	isComposer15: boolean;
	isComposer2: boolean;
	isComposerMatterhorn: boolean;
	isGrok45ProductPrompt: boolean;
	isRawTrainingSlug: boolean;
	reasoningEffort?: string;
	useDsv3Harness: boolean;
	agentTokenLimit?: number;
	estimatedCacheTtlMs?: number;
}

export const RunInferencePromptModelMetadataSchema: MessageCodec<RunInferencePromptModelMetadata> = pb<RunInferencePromptModelMetadata>("aiserver.v1.RunInferencePromptModelMetadata", [
	{ no: 1, name: "vendor", kind: "string" },
	{ no: 2, name: "promptVersion", kind: "string" },
	{ no: 3, name: "isSonnet45", kind: "bool" },
	{ no: 4, name: "isGemini3", kind: "bool" },
	{ no: 5, name: "isGpt51", kind: "bool" },
	{ no: 6, name: "isGpt52", kind: "bool" },
	{ no: 7, name: "isGpt5", kind: "bool" },
	{ no: 8, name: "isGpt55", kind: "bool" },
	{ no: 9, name: "isGpt56", kind: "bool" },
	{ no: 10, name: "isSonnet4", kind: "bool" },
	{ no: 11, name: "isCodexFamily", kind: "bool" },
	{ no: 12, name: "isGpt54", kind: "bool" },
	{ no: 13, name: "isGpt52Codex", kind: "bool" },
	{ no: 14, name: "isGpt53Codex", kind: "bool" },
	{ no: 15, name: "isGpt53CodexSpark", kind: "bool" },
	{ no: 16, name: "isClaude4x", kind: "bool" },
	{ no: 17, name: "isOpus45", kind: "bool" },
	{ no: 18, name: "isOpus46", kind: "bool" },
	{ no: 19, name: "isOpus48", kind: "bool" },
	{ no: 20, name: "isOpus5", kind: "bool" },
	{ no: 21, name: "isFable5", kind: "bool" },
	{ no: 22, name: "isFruitcake", kind: "bool" },
	{ no: 23, name: "isGpt5Family", kind: "bool" },
	{ no: 24, name: "isComposer1", kind: "bool" },
	{ no: 25, name: "isComposer15", kind: "bool" },
	{ no: 26, name: "isComposer2", kind: "bool" },
	{ no: 27, name: "isComposerMatterhorn", kind: "bool" },
	{ no: 28, name: "isGrok45ProductPrompt", kind: "bool" },
	{ no: 29, name: "isRawTrainingSlug", kind: "bool" },
	{ no: 30, name: "reasoningEffort", kind: "string", optional: true },
	{ no: 31, name: "useDsv3Harness", kind: "bool" },
	{ no: 32, name: "agentTokenLimit", kind: "int32", optional: true },
	{ no: 33, name: "estimatedCacheTtlMs", kind: "int32", optional: true },
]);

/** Cursor message aiserver.v1.RunInferenceRoutingMessage. */
export interface RunInferenceRoutingMessage extends ProtoMessage {
	role: RunInferenceRoutingRole;
	text: string;
}

export const RunInferenceRoutingMessageSchema: MessageCodec<RunInferenceRoutingMessage> = pb<RunInferenceRoutingMessage>("aiserver.v1.RunInferenceRoutingMessage", [
	{ no: 1, name: "role", kind: "enum" },
	{ no: 2, name: "text", kind: "string" },
]);

/** Cursor message aiserver.v1.RunInferenceRunReady. */
export interface RunInferenceRunReady extends ProtoMessage {
	resolvedModel?: InferenceRequestedModel;
	supportsSelfSummary: boolean;
	routedModelDisplayName?: string;
	promptModelMetadata?: RunInferencePromptModelMetadata;
}

export const RunInferenceRunReadySchema: MessageCodec<RunInferenceRunReady> = pb<RunInferenceRunReady>("aiserver.v1.RunInferenceRunReady", [
	{ no: 1, name: "resolvedModel", kind: "message", T: () => InferenceRequestedModelSchema },
	{ no: 2, name: "supportsSelfSummary", kind: "bool" },
	{ no: 3, name: "routedModelDisplayName", kind: "string", optional: true },
	{ no: 4, name: "promptModelMetadata", kind: "message", T: () => RunInferencePromptModelMetadataSchema },
]);

/** Cursor message aiserver.v1.RunInferenceRunRequest. */
export interface RunInferenceRunRequest extends ProtoMessage {
	conversationId: string;
	conversationGroupId?: string;
	requestedModel?: InferenceRequestedModel;
	routingConversation: RunInferenceRoutingMessage[];
	agentMode?: string;
}

export const RunInferenceRunRequestSchema: MessageCodec<RunInferenceRunRequest> = pb<RunInferenceRunRequest>("aiserver.v1.RunInferenceRunRequest", [
	{ no: 1, name: "conversationId", kind: "string" },
	{ no: 2, name: "conversationGroupId", kind: "string", optional: true },
	{ no: 3, name: "requestedModel", kind: "message", T: () => InferenceRequestedModelSchema },
	{ no: 4, name: "routingConversation", kind: "message", T: () => RunInferenceRoutingMessageSchema, repeat: true },
	{ no: 5, name: "agentMode", kind: "string", optional: true },
]);

/** Cursor message aiserver.v1.RunInferenceServerMessage. */
export interface RunInferenceServerMessage extends ProtoMessage {
	message:
		| { case: undefined; value?: undefined }
		| { case: "heartbeat"; value: RunInferenceHeartbeat }
		| { case: "runReady"; value: RunInferenceRunReady }
		| { case: "invocationResponse"; value: RunInferenceInvocationResponse }
		| { case: "invocationEnd"; value: RunInferenceInvocationEnd };
}

export const RunInferenceServerMessageSchema: MessageCodec<RunInferenceServerMessage> = pb<RunInferenceServerMessage>("aiserver.v1.RunInferenceServerMessage", [
	{
		kind: "oneof",
		name: "message",
		variants: [
			{ no: 1, name: "heartbeat", kind: "message", T: () => RunInferenceHeartbeatSchema },
			{ no: 2, name: "runReady", kind: "message", T: () => RunInferenceRunReadySchema },
			{ no: 3, name: "invocationResponse", kind: "message", T: () => RunInferenceInvocationResponseSchema },
			{ no: 4, name: "invocationEnd", kind: "message", T: () => RunInferenceInvocationEndSchema },
		],
	},
]);

/** Cursor message agent.v1.ThinkingDetails. */
export interface ThinkingDetails extends ProtoMessage {
}

export const ThinkingDetailsSchema: MessageCodec<ThinkingDetails> = pb<ThinkingDetails>("agent.v1.ThinkingDetails", [
]);

